### ISSUE TITLE
Error in training regarding the gradients

### ISSUE THREAD

**Issue by aryan-f** [Paper99/SRFBN_CVPR19#55]
I'm attempting to train the model on a custom dataset, not previously introduced in the code. For the data, I've copied the LRHR module and replaced a few parts; in the `__init__` method:
```python
# read image list from image/binary files
begin, end = tuple(map(int, self.opt['indices'].split('-')))
self.paths_HR = [os.path.join(self.opt['dataroot_HR'], '{:04}.png'.format(index)) for index in range(begin, end + 1)]
self.paths_LR = [os.path.join(self.opt['dataroot_LR'], '{:04}_x{}_LR.png'.format(index, self.scale)) for index in range(begin, end + 1)]
```
and also:
```python
def name(self):
    split = self.opt['dataroot_LR'].split('/')
    return split[split.index('data') + 1]
```
Now, when I attempt to train the model (on CPU or GPIU) I get `ValueError: optimizing a parameter that doesn't require gradients`! Here are all the parameters returned by `model.parameters()`, namely, their shape and whether they `requires_grad` or not:
```
[(torch.Size([3, 3, 1, 1]), False), (torch.Size([3]), False), (torch.Size([256, 3, 3, 3]), True), (torch.Size([256]), True), (torch.Size([1]), True), (torch.Size([64, 256, 1, 1]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 128, 1, 1]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 64, 6, 6]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 64, 6, 6]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 64, 6, 6]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 64, 6, 6]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 64, 6, 6]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 64, 6, 6]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 64, 6, 6]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 64, 6, 6]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 64, 6, 6]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 64, 6, 6]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 64, 6, 6]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 64, 6, 6]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 128, 1, 1]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 192, 1, 1]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 256, 1, 1]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 320, 1, 1]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 384, 1, 1]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 128, 1, 1]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 192, 1, 1]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 256, 1, 1]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 320, 1, 1]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 384, 1, 1]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 384, 1, 1]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([64, 64, 6, 6]), True), (torch.Size([64]), True), (torch.Size([1]), True), (torch.Size([3, 64, 3, 3]), True), (torch.Size([3]), True), (torch.Size([3, 3, 1, 1]), False), (torch.Size([3]), False)]
```
I should mention that I've made some modifications to the options, as well:
```json
"scale": 2,
"datasets": {
    "train": {
        "mode": "classic",
        "LR_size": 48,
        "data_type": "img",
    },
    "val": {
        "mode": "classic",
        "LR_size": 48,
        "data_type": "img",
    }
}
"networks": {
    "which_model": "SRFBN",
    "num_features": 64,
    "in_channels": 3,
    "out_channels": 3,
    "num_steps": 4,
    "num_groups": 6
}
```
`classic` is the name of the new module I've implemented. But I doubt anything I've changed has anything to do with that. Here's the environment I'm working in:
```
certifi==2020.6.20
cycler==0.10.0
decorator==4.4.2
imageio==2.9.0
kiwisolver==1.2.0
matplotlib==3.3.1
networkx==2.5
numpy==1.19.1
opencv-python==4.4.0.42
pandas==1.1.2
Pillow==7.2.0
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
PyWavelets==1.1.1
scikit-image==0.17.2
scipy==1.1.0
six==1.15.0
tifffile==2020.8.25
torch @ https://download.pytorch.org/whl/cu80/torch-0.4.0-cp36-cp36m-linux_x86_64.whl
torchvision==0.2.2
tqdm==4.19.9
```
Here's the full output:
```
===> CPU mode is set (NOTE: GPU is recommended)
[Warning] Path [experiments/SRFBN_in3f64_x2] already exists. Rename it to [experiments/SRFBN_in3f64_x2_archived_200910-223031]
===> Experimental DIR: [experiments/SRFBN_in3f64_x2]
===> Random Seed: [0]
===> [CLASSIC] Dataset is created.
===> Train Dataset: Draper   Number of images: [9]
===> [CLASSIC] Dataset is created.
===> Val Dataset: Draper   Number of images: [9]
===> Building network [SRFBN]...
Traceback (most recent call last):
  File "./train.py", line 131, in <module>
    main()
  File "./train.py", line 41, in main
    solver = create_solver(opt)
  File "./solvers/__init__.py", line 5, in create_solver
    solver = SRSolver(opt)
  File "./solvers/SRSolver.py", line 57, in __init__
    lr=self.train_opt['learning_rate'], weight_decay=weight_decay)
  File "../environments/torch04/lib/python3.6/site-packages/torch/optim/adam.py", line 41, in __init__
    super(Adam, self).__init__(params, defaults)
  File "../environments/torch04/lib/python3.6/site-packages/torch/optim/optimizer.py", line 43, in __init__
    self.add_param_group(param_group)
  File "../environments/torch04/lib/python3.6/site-packages/torch/optim/optimizer.py", line 193, in add_param_group
    raise ValueError("optimizing a parameter that doesn't require gradients")
ValueError: optimizing a parameter that doesn't require gradients
```

**Comment by aryan-f** [comment]
Tried a workaround for the problem. Added a little loop before the optimizer gets defined to set `requires_grad` to `True` for all parameters, and then received an error on `torch` having no function called `interpolate`. Switched to an environment with PyTorch 1.1.0 and CUDA 10, and everything started working. I think you should edit the README.
