### ISSUE TITLE
How to use other data such as 291 dataset  to train?

### ISSUE THREAD

**Issue by zdyshine** [Paper99/SRFBN_CVPR19#8]
Thanks your project, but when I use 291 dataset to train, I get error:

===> Training Epoch: [1/1000]...  Learning Rate: 0.000100
Epoch: [1/1000]:   0%|                                                                         | 0/114 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 131, in <module>
    main()
  File "train.py", line 67, in main
    for iter, batch in enumerate(train_loader):
  File "C:\Users\h439\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "C:\Users\h439\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "C:\Users\h439\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\h439\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "E:\DYng_Z\3-image_super\code\SRFBN_CVPR19\data\LRHR_dataset.py", line 40, in __getitem__
    lr, hr = self._get_patch(lr, hr)
  File "E:\DYng_Z\3-image_super\code\SRFBN_CVPR19\data\LRHR_dataset.py", line 74, in _get_patch
    lr, hr, LR_size, self.scale)
  File "E:\DYng_Z\3-image_super\code\SRFBN_CVPR19\data\common.py", line 134, in get_patch
    ix = random.randrange(0, iw - ip + 1)
  File "C:\Users\h439\Anaconda3\lib\random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,-5, -5)

I have no idea how to solve it. Can you help me?

**Comment by Paper99** [comment]
The size of your LR image is smaller than `LR_size` in `*.json`.

**Comment by zdyshine** [comment]
Thanks, I can use it now.

**Comment by Senwang98** [comment]
@Paper99 I meet this problem too, I want to know how to set appropriate value of LR_SIZE?
I also wan to know if this value will affect the result of final model?
